server:
  port: 8012
spring:
  application:
    name: config-service
  rabbitmq:
      host: localhost
      port: 5672
      username: serfer
      password: Fkg7h4f$
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Gondagar/udemy-configuration.git
          username: serhey.moskalenko@gmail.com
          password: Fkg7h4f3$
          clone-on-start: true
          skip-ssl-validation: true
management:
  endpoint:
    web:
      exposure:
        include: bus-refresh

